import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import { store } from './_app'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const error = store.getState().error.value
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>Home</div>
        <Link href="/users">Users Page</Link>
        <div>{error}</div>
      </main>
    </>
  )
}
