import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import { useSelector } from 'react-redux';
import { RootState } from '@/contexts/store';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const error = useSelector((state: RootState) => state.error.value);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>Home</div>
        <Link href="/users">Users Page</Link>
        {error && <div>{error}</div>}
      </main>
    </>
  );
}
